Clients/MvcApp/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcApp.Models;
using MvcApp.ViewModels;

namespace MvcApp.Controllers
{
    [Route("[controller]")]
    public class AuthController : Controller
    {


        private readonly AuthServiceModel _service;
        private readonly IConfiguration _config;

        public AuthController(IConfiguration config)
        {
            _config = config;

            _service = new AuthServiceModel(_config);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View("Index");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(RegisterViewModel model)
        {
            try
            {

                await _service.RegisterUser(model);
                return View(model);

            }
            catch (Exception)
            {

                return StatusCode(500, "Något gick fel! Vi kunde inte registrera användaren! Kontrollera din informationen och försök igen.");
            }
        }
    }
}

Clients/MvcApp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcApp.Models;
using MvcApp.ViewModels.Categories;
using MvcApp.ViewModels.Courses;

namespace MvcApp.Controllers
{
    [Route("[controller]")]
    public class CategoriesController : Controller
    {

        private readonly IConfiguration _config;
        private readonly CategoryServiceModel _service;
        public CategoriesController(IConfiguration config)
        {
            _config = config;
            _service = new CategoryServiceModel(_config);
        }

        public async Task<IActionResult> Index()
        {
            try
            {

                var categories = await _service.ListCategories();
                return View("Index", categories);
            }
            catch (Exception)
            {

                return StatusCode(500, "Något gick snätt! vi kunde inte hämta kategorilistan.. ");
            }

        }

    }
}

Clients/MvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" />


    <title>Westcoast Education - @ViewBag.PageTitle</title>
</head>
<body>
    <section class="top-nav">
        <div>
            <a id="logo" asp-controller="Home"><i class="fa-solid fa-graduation-cap"></i> Westcoast Education</a>
        </div>
        <input id="menu-toggle" type="checkbox" />
        <label class='menu-button-container' for="menu-toggle">
            <div class='menu-button'></div>
        </label>
        <ul class="menu">
            <li><a asp-controller="Home" asp-action="Index">Start</a></li>
            <li><a asp-controller="Categories" asp-action="Index">Våra kurser</a></li>
            <li><a asp-controller="Auth" asp-action="Index">Registrera</a></li>
            <li><a asp-controller="Home" asp-action="About">Om oss</a></li>
        </ul>
    </section>
    <main>
        @RenderBody()

    </main>

</body>
<footer>Westcoast Education 2022 <a asp-controller="Home" asp-action="About">Om oss</a></footer>
</html>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)